# Generated by Django 4.2.23 on 2025-08-15 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_time', models.CharField(default='1일', help_text='예: "월/수 4시간, 1달" - 사용자가 한 칸에 입력', max_length=100)),
                ('payment_info', models.CharField(default='시급 10000원', help_text='예: "10000원" 또는 "2시간" - 사용자가 한 칸에 입력', max_length=100)),
                ('payment_type', models.CharField(choices=[('LOCAL_CURRENCY', '지역화폐'), ('VOLUNTEER_TIME', '봉사시간')], help_text='봉사시간 또는 지역화폐 선택', max_length=20)),
                ('description', models.TextField(max_length=300)),
                ('image_from_gallery', models.ImageField(blank=True, null=True, upload_to='job_images/gallery/')),
                ('image_from_ai', models.ImageField(blank=True, null=True, upload_to='job_images/ai/')),
                ('store_lat', models.FloatField()),
                ('store_lng', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liked_users', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobpost')),
            ],
        ),
    ]
