# Generated by Django 4.2.23 on 2025-08-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='motivation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
