# Generated by Django 4.2.23 on 2025-08-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('accepted', '수락'), ('rejected', '거절'), ('matched', '매칭완료'), ('completed', '작업완료')], default='pending', max_length=20),
        ),
    ]
