# Generated by Django 4.2.23 on 2025-08-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
