# Generated by Django 4.2.23 on 2025-08-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_is_verified_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='store_name',
            new_name='ceo_name',
        ),
    ]
