# Generated by Django 4.2.23 on 2025-08-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='business_cert',
        ),
    ]
