# Generated by Django 4.2.23 on 2025-08-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_business_cert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='double_major',
        ),
    ]
