# Generated by Django 4.2.23 on 2025-08-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_profile_double_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skill_2',
            field=models.CharField(blank=True, choices=[('design', '디자인'), ('photo_video', '영상/사진'), ('craft', '공예'), ('coding', '코딩/개발'), ('language', '외국어/번역'), ('marketing', '홍보/마케팅'), ('document', '문서 작성'), ('counsel', '상담'), ('volunteer', '자원봉사')], max_length=20, null=True),
        ),
    ]
