# Generated by Django 4.2.23 on 2025-08-18 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation', models.PositiveSmallIntegerField()),
                ('diligence', models.PositiveSmallIntegerField()),
                ('punctuality', models.PositiveSmallIntegerField()),
                ('cheerful_attitude', models.PositiveSmallIntegerField()),
                ('politeness', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_reviews', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_reviews', to='jobs.jobpost')),
            ],
            options={
                'unique_together': {('employee', 'job')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_reviews', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_reviews', to='jobs.jobpost')),
            ],
            options={
                'unique_together': {('employee', 'job')},
            },
        ),
    ]
