# Generated by Django 4.2.23 on 2025-08-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerreview',
            name='participation',
        ),
    ]
