# Generated by Django 4.2.23 on 2025-08-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrequest',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('accepted', '수락'), ('rejected', '거절'), ('matched', '매칭완료'), ('completed', '작업완료')], default='pending', max_length=20),
        ),
    ]
