# Generated by Django 4.2.23 on 2025-08-21 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_alter_application_status'),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedstudent',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for_students', to='jobs.jobpost'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendedjobpost',
            unique_together={('job_post', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='recommendedstudent',
            unique_together={('job_post', 'student')},
        ),
    ]
