# Generated by Django 4.2.23 on 2025-08-21 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_application_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0002_alter_recommendedstudent_job_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequeset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기'), ('accepted', '수락'), ('rejected', '거절')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests', to='jobs.jobpost')),
            ],
        ),
        migrations.DeleteModel(
            name='TalentRequest',
        ),
    ]
