# Generated by Django 4.2.23 on 2025-08-21 21:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_alter_application_status'),
        ('matching', '0003_matchrequeset_delete_talentrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchRequeset',
            new_name='MatchRequest',
        ),
    ]
