# Generated by Django 4.2.23 on 2025-08-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='show_for_recommendation',
            field=models.BooleanField(default=True),
        ),
    ]
