# Generated by Django 4.2.23 on 2025-08-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('portfolio', '0002_portfolio_show_for_recommendation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activites',
            new_name='Activities',
        ),
    ]
