# Generated by Django 4.2.23 on 2025-08-19 15:15

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_activites_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.profile_upload_path),
        ),
        migrations.AlterField(
            model_name='talentimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.talent_upload_path),
        ),
    ]
